[project]
name = "jango-crud-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=5.2.8",
    "psycopg2-binary>=2.9.11",
]
